/** Auto-generated by scripts/generate-wardogs-forums.mjs — edit the script and re-run. */
export type BlogSection = {
  heading: string
  body: string[]
}

export type BlogPost = {
  slug: string
  title: string
  excerpt: string
  metaTitle: string
  metaDescription: string
  searchTerms: string
  date: string
  readMinutes: number
  tag: string
  sections: BlogSection[]
  howTo?: boolean
}

export const BLOGS: BlogPost[] = [
  {
    "slug": "features-list",
    "title": "Wardogs Cheats Features",
    "excerpt": "Full module checklist for Wardogs cheats on PC — aimbot, player ESP, vehicle overlays, 2D radar, and config tools before you open checkout.",
    "metaTitle": "Wardogs Cheats Features | Full Feature Overview",
    "metaDescription": "Full module checklist for Wardogs cheats on PC — aimbot, player ESP, vehicle overlays, 2D radar, and config tools before you open checkout.",
    "searchTerms": "Wardogs cheat features, Wardogs tools, Wardogs features, Wardogs cheats",
    "date": "2026-09-12",
    "readMinutes": 6,
    "tag": "Features",
    "sections": [
      {
        "heading": "What the menu includes",
        "body": [
          "This thread mirrors the live module list on cheatforwardogs.net. Use it to compare aimbot, ESP, vehicle, radar, and misc toggles against what you need in control-zone fights.",
          "Wardogs runs large lobbies with vehicles and three-team pressure — the feature set focuses on player awareness, transport intel, and optional combat assist rather than loot simulators."
        ]
      },
      {
        "heading": "Aimbot, visuals, radar",
        "body": [
          "Aimbot options cover enable, FOV, smooth, bone selection, visible check, prediction, draw FOV, and draw target line.",
          "Player visuals include box, skeleton, head circle, health bar, distance, name, team/squad, weapon, view direction, OOF arrows, and max distance.",
          "Vehicle visuals, 2D radar markers, and misc no recoil / no spread / full bright / custom crosshair / config save-load round out the stack."
        ]
      }
    ]
  },
  {
    "slug": "complete-setup",
    "title": "Instructions to Use the Cheats",
    "excerpt": "Step-by-step Wardogs cheat setup on Windows: confirm Active status, exclusions, load order, first ESP profile, optional aimbot, save config.",
    "metaTitle": "Instructions to Use the Cheats | Wardogs Cheats Forum",
    "metaDescription": "Step-by-step Wardogs cheat setup on Windows: confirm Active status, exclusions, load order, first ESP profile, optional aimbot, save config.",
    "searchTerms": "get wardogs cheats, get wardogs cheat, wardogs cheats",
    "date": "2026-09-13",
    "readMinutes": 7,
    "tag": "Setup",
    "sections": [
      {
        "heading": "1) Confirm status and checkout",
        "body": [
          "Open cheatforwardogs.net and check Active on the product card. When Updating after a Wardogs patch, wait — loading early wastes a session.",
          "Plans start from $35 monthly with lifetime options; use only the delivery link from your order email."
        ]
      },
      {
        "heading": "2) Windows prep",
        "body": [
          "Close Discord overlay, GeForce overlay, and RGB hooks. Add the delivery folder to Defender exclusions before first inject."
        ]
      },
      {
        "heading": "3) Load order",
        "body": [
          "Launch Wardogs from Steam, reach the main menu, run the loader, open the menu, enable player ESP and radar, then add aimbot only if you want assist."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "aimbot-settings",
    "title": "Aimbot Settings: What Level & Why Won’t I Get Banned?",
    "excerpt": "Tune Wardogs aimbot FOV, smooth, and visible check so tracking helps in control-zone fights without obvious kill-cam clips.",
    "metaTitle": "Aimbot Settings: What Level & Why Won’t I Get Banned? | Wardogs Cheats Forum",
    "metaDescription": "Tune Wardogs aimbot FOV, smooth, and visible check so tracking helps in control-zone fights without obvious kill-cam clips.",
    "searchTerms": "wardogs aimbot, buy wardogs aimbot, wardogs aimbot lifetime",
    "date": "2026-09-14",
    "readMinutes": 8,
    "tag": "Aimbot",
    "sections": [
      {
        "heading": "Start conservative",
        "body": [
          "Wide FOV and zero smooth get reported fast — players review deaths in a 100-player lobby. Start small FOV, higher smooth, body bones first.",
          "Visible check stops tracking through solid cover; keep it on unless you accept more reports."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "esp-wallhack-guide",
    "title": "Player ESP Settings: What to Enable First",
    "excerpt": "Configure Wardogs player ESP — box, skeleton, distance, weapon, team filter — without cluttering your HUD in mountain fights.",
    "metaTitle": "Player ESP Settings: What to Enable First | Wardogs Cheats Forum",
    "metaDescription": "Configure Wardogs player ESP — box, skeleton, distance, weapon, team filter — without cluttering your HUD in mountain fights.",
    "searchTerms": "wardogs esp, buy wardogs esp, wardogs esp lifetime",
    "date": "2026-09-15",
    "readMinutes": 9,
    "tag": "ESP",
    "sections": [
      {
        "heading": "Recommended first toggles",
        "body": [
          "Enable box, distance, and name. Add weapon ESP when you rotate solo — DMR vs SMG changes peek timing at 40m.",
          "Cap max distance around 150–200m so tags stay readable during control-zone pushes."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "vehicle-esp-first",
    "title": "Vehicle ESP Settings: What to Enable First",
    "excerpt": "Vehicle ESP type, distance, and occupied/empty indicators for Wardogs — spot transports before you cross open ground.",
    "metaTitle": "Vehicle ESP Settings: What to Enable First | Wardogs Cheats Forum",
    "metaDescription": "Vehicle ESP type, distance, and occupied/empty indicators for Wardogs — spot transports before you cross open ground.",
    "searchTerms": "wardogs esp",
    "date": "2026-09-16",
    "readMinutes": 10,
    "tag": "Vehicles",
    "sections": [
      {
        "heading": "Priority toggles",
        "body": [
          "Turn on vehicle ESP with type labels and occupied/empty state. Distance under 300m keeps the overlay clean.",
          "Pair with 2D radar vehicle markers when your squad splits — one player on foot still sees convoy movement."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "radar-recommended-config",
    "title": "2D Radar & Control Zone: Recommended Configurations",
    "excerpt": "2D radar range, player markers, and vehicle markers tuned for Wardogs control-zone rotations and third-party sound.",
    "metaTitle": "2D Radar & Control Zone: Recommended Configurations | Wardogs Cheats Forum",
    "metaDescription": "2D radar range, player markers, and vehicle markers tuned for Wardogs control-zone rotations and third-party sound.",
    "searchTerms": "wardogs esp",
    "date": "2026-09-17",
    "readMinutes": 6,
    "tag": "Radar",
    "sections": [
      {
        "heading": "Radar defaults",
        "body": [
          "Start radar range medium — too wide floods the minimap in dense fights. Player markers on, vehicle markers on for hill rotations.",
          "Drop range when pushing buildings so arrows match audible footsteps."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "combat-assist-settings",
    "title": "Combat Assist Settings: What Level & Ban Risk Explained",
    "excerpt": "Balance aimbot smooth, FOV, and ESP noise for Wardogs ranked-style queues — report habits and kill cam reality.",
    "metaTitle": "Combat Assist Settings: What Level & Ban Risk Explained | Wardogs Cheats Forum",
    "metaDescription": "Balance aimbot smooth, FOV, and ESP noise for Wardogs ranked-style queues — report habits and kill cam reality.",
    "searchTerms": "wardogs aimbot",
    "date": "2026-09-18",
    "readMinutes": 7,
    "tag": "Combat",
    "sections": [
      {
        "heading": "Reports matter",
        "body": [
          "Players flag snap deaths and impossible prefires. ESP-only nights plus low smooth aimbot beat max settings in week one."
        ]
      }
    ]
  },
  {
    "slug": "game-patch-status",
    "title": "Wardogs Cheats After a Game Patch — What to Do",
    "excerpt": "What Active vs Updating means after Wardogs patches — and why loading early wastes your control-zone session.",
    "metaTitle": "Wardogs Cheats After a Game Patch — What to Do | Wardogs Cheats Forum",
    "metaDescription": "What Active vs Updating means after Wardogs patches — and why loading early wastes your control-zone session.",
    "searchTerms": "wardogs cheats, wardogs anti",
    "date": "2026-09-19",
    "readMinutes": 8,
    "tag": "Status",
    "sections": [
      {
        "heading": "Status labels",
        "body": [
          "Active means the loader matches the live client. Updating means wait — check cheatforwardogs.net before every session."
        ]
      }
    ]
  },
  {
    "slug": "ultimate-wardogs-cheats-guide",
    "title": "Ultimate Wardogs Cheats Guide: Setup & Features",
    "excerpt": "Overview of Wardogs cheat modules, loader status, and first-night config for control-zone and vehicle fights on PC.",
    "metaTitle": "Ultimate Wardogs Cheats Guide: Setup & Features | Wardogs Cheats Forum",
    "metaDescription": "Overview of Wardogs cheat modules, loader status, and first-night config for control-zone and vehicle fights on PC.",
    "searchTerms": "wardogs cheats, wardogs esp, wardogs aimbot, wardogs anti",
    "date": "2026-09-20",
    "readMinutes": 9,
    "tag": "Guide",
    "sections": [
      {
        "heading": "Feature map",
        "body": [
          "Aimbot, player ESP, vehicle ESP, 2D radar, and misc weapon helpers — match toggles to how your trio rotates hills and roads."
        ]
      }
    ]
  },
  {
    "slug": "buy-wardogs-cheats-safely",
    "title": "Where to Buy Wardogs Cheats Safely: Full Access Options",
    "excerpt": "How to buy Wardogs cheats with clear pricing, digital delivery, and status labels before you load into a 100-player lobby.",
    "metaTitle": "Where to Buy Wardogs Cheats Safely: Full Access Options | Wardogs Cheats Forum",
    "metaDescription": "How to buy Wardogs cheats with clear pricing, digital delivery, and status labels before you load into a 100-player lobby.",
    "searchTerms": "buy wardogs cheats, buy wardogs cheat, buy wardogs esp, buy wardogs aimbot",
    "date": "2026-09-21",
    "readMinutes": 10,
    "tag": "Buying",
    "sections": [
      {
        "heading": "Before checkout",
        "body": [
          "Use cheatforwardogs.net for live Active/Updating status. Monthly and lifetime licenses include loader updates when status allows."
        ]
      }
    ]
  },
  {
    "slug": "wardogs-cheats-lifetime",
    "title": "Wardogs Cheats Lifetime License: Is Permanent Access Worth It?",
    "excerpt": "Lifetime vs monthly Wardogs cheat access — when permanent makes sense for regular control-zone players.",
    "metaTitle": "Wardogs Cheats Lifetime License: Is Permanent Access Worth It? | Wardogs Cheats Forum",
    "metaDescription": "Lifetime vs monthly Wardogs cheat access — when permanent makes sense for regular control-zone players.",
    "searchTerms": "wardogs cheats lifetime, wardogs cheat lifetime, wardogs aimbot lifetime, wardogs esp lifetime",
    "date": "2026-09-12",
    "readMinutes": 6,
    "tag": "Pricing",
    "sections": [
      {
        "heading": "Who lifetime fits",
        "body": [
          "If you play multiple nights per week through seasons, lifetime offsets monthly renewals. Casual players often start monthly first."
        ]
      }
    ]
  },
  {
    "slug": "wardogs-cheat-discord",
    "title": "Official Wardogs Cheat Discord Server: How to Join for Live Support",
    "excerpt": "Find live Wardogs cheat support channels after purchase — status pings, config screenshots, and patch-day threads.",
    "metaTitle": "Official Wardogs Cheat Discord Server: How to Join for Live Support | Wardogs Cheats Forum",
    "metaDescription": "Find live Wardogs cheat support channels after purchase — status pings, config screenshots, and patch-day threads.",
    "searchTerms": "wardogs cheat discord",
    "date": "2026-09-13",
    "readMinutes": 7,
    "tag": "Community",
    "sections": [
      {
        "heading": "What Discord is for",
        "body": [
          "Discord complements the forums here — quick loader screenshots and patch chatter. Purchase still flows through the store link on the product page."
        ]
      }
    ]
  },
  {
    "slug": "best-wardogs-cheats-review-2026",
    "title": "Wardogs Cheats Review 2026: Features, Safety & Value",
    "excerpt": "2026 Wardogs cheats review — ESP clarity, aimbot tuning, vehicle radar, pricing, and loader maintenance on cheatforwardogs.net.",
    "metaTitle": "Wardogs Cheats Review 2026: Features, Safety & Value | Wardogs Cheats Forum",
    "metaDescription": "2026 Wardogs cheats review — ESP clarity, aimbot tuning, vehicle radar, pricing, and loader maintenance on cheatforwardogs.net.",
    "searchTerms": "wardogs cheats, buy wardogs cheats, wardogs cheats lifetime",
    "date": "2026-09-14",
    "readMinutes": 8,
    "tag": "Review",
    "sections": [
      {
        "heading": "What we compared",
        "body": [
          "Module depth, config save/load, status transparency, and how fast ESP recovered after game patches — not hype claims."
        ]
      }
    ]
  },
  {
    "slug": "hwid-spoofer-safety",
    "title": "Discover What an HWID Spoofer Does for Safety",
    "excerpt": "HWID spoofer basics for PC gamers — what hardware IDs are, why some players research them, and realistic limits.",
    "metaTitle": "Discover What an HWID Spoofer Does for Safety | Wardogs Cheats Forum",
    "metaDescription": "HWID spoofer basics for PC gamers — what hardware IDs are, why some players research them, and realistic limits.",
    "searchTerms": "wardogs anti",
    "date": "2026-09-15",
    "readMinutes": 9,
    "tag": "Safety",
    "sections": [
      {
        "heading": "Plain-language overview",
        "body": [
          "A spoofer changes how your PC fingerprint appears to some anti-cheat stacks. It is not a substitute for reading loader status or playing conservatively."
        ]
      }
    ]
  },
  {
    "slug": "wardogs-aimbot-options",
    "title": "Precision Target Lock: Mastering Wardogs Aimbot Options",
    "excerpt": "Deep dive on Wardogs aimbot enable, FOV, smooth, bones, visible check, and prediction.",
    "metaTitle": "Precision Target Lock: Mastering Wardogs Aimbot Options | Wardogs Cheats Forum",
    "metaDescription": "Deep dive on Wardogs aimbot enable, FOV, smooth, bones, visible check, and prediction.",
    "searchTerms": "wardogs aimbot",
    "date": "2026-09-16",
    "readMinutes": 10,
    "tag": "Aimbot",
    "sections": [
      {
        "heading": "Core toggles",
        "body": [
          "Work FOV down before touching prediction — leading targets matters most on moving vehicles."
        ]
      }
    ]
  },
  {
    "slug": "enable-aimbot-safely",
    "title": "How to Configure and Enable Aimbot Safely in Wardogs",
    "excerpt": "Enable aimbot only after ESP and radar baselines — bind toggles and test in offline range first.",
    "metaTitle": "How to Configure and Enable Aimbot Safely in Wardogs | Wardogs Cheats Forum",
    "metaDescription": "Enable aimbot only after ESP and radar baselines — bind toggles and test in offline range first.",
    "searchTerms": "wardogs aimbot",
    "date": "2026-09-17",
    "readMinutes": 6,
    "tag": "Aimbot",
    "sections": [
      {
        "heading": "Enable order",
        "body": [
          "Player ESP on, visible check on, then enable aimbot with high smooth."
        ]
      }
    ]
  },
  {
    "slug": "aimbot-fov-settings",
    "title": "Dialing in Your Field of View Settings for Natural Aiming",
    "excerpt": "FOV cone sizing for CQB buildings vs open hills in Wardogs.",
    "metaTitle": "Dialing in Your Field of View Settings for Natural Aiming | Wardogs Cheats Forum",
    "metaDescription": "FOV cone sizing for CQB buildings vs open hills in Wardogs.",
    "searchTerms": "Wardogs Aimbot, aimbot fov settings, Wardogs cheats",
    "date": "2026-09-18",
    "readMinutes": 7,
    "tag": "Aimbot",
    "sections": [
      {
        "heading": "FOV tips",
        "body": [
          "Draw FOV helps you see the cone — keep it smaller than your reflex FOV."
        ]
      }
    ]
  },
  {
    "slug": "aimbot-smooth-guide",
    "title": "How Smooth Aiming Keeps Your Gameplay Looking Legitimate",
    "excerpt": "Smooth values that reduce snap on kill cams without feeling sluggish.",
    "metaTitle": "How Smooth Aiming Keeps Your Gameplay Looking Legitimate | Wardogs Cheats Forum",
    "metaDescription": "Smooth values that reduce snap on kill cams without feeling sluggish.",
    "searchTerms": "Wardogs Aimbot, aimbot smooth guide, Wardogs cheats",
    "date": "2026-09-19",
    "readMinutes": 8,
    "tag": "Aimbot",
    "sections": [
      {
        "heading": "Smoothing",
        "body": [
          "Higher smooth on DMR, moderate on AR — save profiles per weapon class."
        ]
      }
    ]
  },
  {
    "slug": "bone-selection-guide",
    "title": "Targeted Bone Selection Guide: Headshots vs Body Shots",
    "excerpt": "Bone selection tradeoffs for moving targets and armored foes.",
    "metaTitle": "Targeted Bone Selection Guide: Headshots vs Body Shots | Wardogs Cheats Forum",
    "metaDescription": "Bone selection tradeoffs for moving targets and armored foes.",
    "searchTerms": "Wardogs Aimbot, bone selection guide, Wardogs cheats",
    "date": "2026-09-20",
    "readMinutes": 9,
    "tag": "Aimbot",
    "sections": [
      {
        "heading": "Bones",
        "body": [
          "Chest default for moving tags; head bone only when smooth is high enough."
        ]
      }
    ]
  },
  {
    "slug": "visible-check-guide",
    "title": "Preventing Wall Tracking: Why Visible Check Is Essential",
    "excerpt": "Visible check stops locks through metal walls — use it in urban control zones.",
    "metaTitle": "Preventing Wall Tracking: Why Visible Check Is Essential | Wardogs Cheats Forum",
    "metaDescription": "Visible check stops locks through metal walls — use it in urban control zones.",
    "searchTerms": "Wardogs Aimbot, visible check guide, Wardogs cheats",
    "date": "2026-09-21",
    "readMinutes": 10,
    "tag": "Aimbot",
    "sections": [
      {
        "heading": "Visible check",
        "body": [
          "Without it, kill cams show pre-fire through cover — reports stack fast."
        ]
      }
    ]
  },
  {
    "slug": "bullet-prediction",
    "title": "Leading Your Shots: Bullet Prediction Mechanics Explained",
    "excerpt": "Prediction for sprinting targets and vehicle exits in Wardogs.",
    "metaTitle": "Leading Your Shots: Bullet Prediction Mechanics Explained | Wardogs Cheats Forum",
    "metaDescription": "Prediction for sprinting targets and vehicle exits in Wardogs.",
    "searchTerms": "Wardogs Aimbot, bullet prediction, Wardogs cheats",
    "date": "2026-09-12",
    "readMinutes": 6,
    "tag": "Aimbot",
    "sections": [
      {
        "heading": "Prediction",
        "body": [
          "Tune after FOV/smooth — prediction magnifies mistakes if base aim is too aggressive."
        ]
      }
    ]
  },
  {
    "slug": "draw-fov-overlays",
    "title": "Visualizing Your Aim Radius: How to Use Draw FOV Overlays",
    "excerpt": "Draw FOV circle usage without blocking center crosshair vision.",
    "metaTitle": "Visualizing Your Aim Radius: How to Use Draw FOV Overlays | Wardogs Cheats Forum",
    "metaDescription": "Draw FOV circle usage without blocking center crosshair vision.",
    "searchTerms": "Wardogs Aimbot, draw fov overlays, Wardogs cheats",
    "date": "2026-09-13",
    "readMinutes": 7,
    "tag": "Aimbot",
    "sections": [
      {
        "heading": "Draw FOV",
        "body": [
          "Thin white circle matches most HUDs — disable for clips if teammates watch."
        ]
      }
    ]
  },
  {
    "slug": "draw-target-line",
    "title": "Target Line Visuals: Instantly Identify Locked Enemies",
    "excerpt": "Target line overlays show which tag aimbot selected in crowded fights.",
    "metaTitle": "Target Line Visuals: Instantly Identify Locked Enemies | Wardogs Cheats Forum",
    "metaDescription": "Target line overlays show which tag aimbot selected in crowded fights.",
    "searchTerms": "Wardogs Aimbot, draw target line, Wardogs cheats",
    "date": "2026-09-14",
    "readMinutes": 8,
    "tag": "Aimbot",
    "sections": [
      {
        "heading": "Target line",
        "body": [
          "Helpful in trios when three tags stack — turn off for solo stealth play."
        ]
      }
    ]
  },
  {
    "slug": "player-visuals-breakdown",
    "title": "Complete Player Visuals Breakdown for Tactical Dominance",
    "excerpt": "Every player visual toggle explained for Wardogs three-team lobbies.",
    "metaTitle": "Complete Player Visuals Breakdown for Tactical Dominance | Wardogs Cheats Forum",
    "metaDescription": "Every player visual toggle explained for Wardogs three-team lobbies.",
    "searchTerms": "wardogs esp, buy wardogs esp, wardogs esp lifetime",
    "date": "2026-09-15",
    "readMinutes": 9,
    "tag": "ESP",
    "sections": [
      {
        "heading": "Player visuals",
        "body": [
          "Mix box + skeleton sparingly — pick one primary outline to reduce noise."
        ]
      }
    ]
  },
  {
    "slug": "box-esp-setup",
    "title": "Box ESP Setup: 2D vs 3D Bounding Boxes for Target Tracking",
    "excerpt": "Box ESP styles for long-range hill fights vs close building clears.",
    "metaTitle": "Box ESP Setup: 2D vs 3D Bounding Boxes for Target Tracking | Wardogs Cheats Forum",
    "metaDescription": "Box ESP styles for long-range hill fights vs close building clears.",
    "searchTerms": "wardogs esp",
    "date": "2026-09-16",
    "readMinutes": 10,
    "tag": "ESP",
    "sections": [
      {
        "heading": "Boxes",
        "body": [
          "2D boxes read faster at distance; 3D helps when targets sit on stairs."
        ]
      }
    ]
  },
  {
    "slug": "skeleton-esp-guide",
    "title": "Skeleton ESP: Real-Time Stance and Movement Overlay Guide",
    "excerpt": "Skeleton overlays show crouch vs standing through windows before you push.",
    "metaTitle": "Skeleton ESP: Real-Time Stance and Movement Overlay Guide | Wardogs Cheats Forum",
    "metaDescription": "Skeleton overlays show crouch vs standing through windows before you push.",
    "searchTerms": "wardogs esp",
    "date": "2026-09-17",
    "readMinutes": 6,
    "tag": "ESP",
    "sections": [
      {
        "heading": "Skeleton",
        "body": [
          "Mute skeleton color — neon green reads obvious on recordings."
        ]
      }
    ]
  },
  {
    "slug": "head-circle-visuals",
    "title": "Head Circle Visuals: Instant Headshot Alignment Overlays",
    "excerpt": "Head circle pairing with low smooth aimbot for DMR players.",
    "metaTitle": "Head Circle Visuals: Instant Headshot Alignment Overlays | Wardogs Cheats Forum",
    "metaDescription": "Head circle pairing with low smooth aimbot for DMR players.",
    "searchTerms": "Wardogs ESP, head circle visuals, Wardogs cheats",
    "date": "2026-09-18",
    "readMinutes": 7,
    "tag": "ESP",
    "sections": [
      {
        "heading": "Head circle",
        "body": [
          "Combine with visible check so you only pre-aim visible peeks."
        ]
      }
    ]
  },
  {
    "slug": "health-bar-tracking",
    "title": "Enemy Health Bar Tracking: Prioritize Low-HP Targets",
    "excerpt": "Health bars help focus fire in squad wipes during control-zone cash fights.",
    "metaTitle": "Enemy Health Bar Tracking: Prioritize Low-HP Targets | Wardogs Cheats Forum",
    "metaDescription": "Health bars help focus fire in squad wipes during control-zone cash fights.",
    "searchTerms": "Wardogs ESP, health bar tracking, Wardogs cheats",
    "date": "2026-09-19",
    "readMinutes": 8,
    "tag": "ESP",
    "sections": [
      {
        "heading": "Health bars",
        "body": [
          "Vertical bars beside boxes — disable on max distance tags to save clutter."
        ]
      }
    ]
  },
  {
    "slug": "distance-esp-indicators",
    "title": "Distance ESP Indicators: Judging Combat Ranges Effectively",
    "excerpt": "Distance readouts for picking SMG vs DMR engagements on roads.",
    "metaTitle": "Distance ESP Indicators: Judging Combat Ranges Effectively | Wardogs Cheats Forum",
    "metaDescription": "Distance readouts for picking SMG vs DMR engagements on roads.",
    "searchTerms": "Wardogs ESP, distance esp indicators, Wardogs cheats",
    "date": "2026-09-20",
    "readMinutes": 9,
    "tag": "ESP",
    "sections": [
      {
        "heading": "Distance",
        "body": [
          "Sort mentally: under 30m push, 30–80m hold angle, 80m+ mark for squad."
        ]
      }
    ]
  },
  {
    "slug": "player-name-tags",
    "title": "Player Name Tags: Identifying High-Value Targets In-Game",
    "excerpt": "Name ESP for remembering repeat third parties in long sessions.",
    "metaTitle": "Player Name Tags: Identifying High-Value Targets In-Game | Wardogs Cheats Forum",
    "metaDescription": "Name ESP for remembering repeat third parties in long sessions.",
    "searchTerms": "Wardogs ESP, player name tags, Wardogs cheats",
    "date": "2026-09-21",
    "readMinutes": 10,
    "tag": "ESP",
    "sections": [
      {
        "heading": "Names",
        "body": [
          "Screenshot names only in Discord DMs — avoid public callouts."
        ]
      }
    ]
  },
  {
    "slug": "team-squad-filtering",
    "title": "Team & Squad Visual Filtering: Avoid Screen Clutter",
    "excerpt": "Team/squad filters so friendly markers do not mask enemies.",
    "metaTitle": "Team & Squad Visual Filtering: Avoid Screen Clutter | Wardogs Cheats Forum",
    "metaDescription": "Team/squad filters so friendly markers do not mask enemies.",
    "searchTerms": "Wardogs ESP, team squad filtering, Wardogs cheats",
    "date": "2026-09-12",
    "readMinutes": 6,
    "tag": "ESP",
    "sections": [
      {
        "heading": "Team filter",
        "body": [
          "Color allies blue, enemies red — verify squad IDs after matchmaking."
        ]
      }
    ]
  },
  {
    "slug": "enemy-weapon-esp",
    "title": "Enemy Weapon ESP: Spotting High-Tier Guns Instantly",
    "excerpt": "Weapon ESP tells you when a tag carries a DMR worth pushing or avoiding.",
    "metaTitle": "Enemy Weapon ESP: Spotting High-Tier Guns Instantly | Wardogs Cheats Forum",
    "metaDescription": "Weapon ESP tells you when a tag carries a DMR worth pushing or avoiding.",
    "searchTerms": "Wardogs ESP, enemy weapon esp, Wardogs cheats",
    "date": "2026-09-13",
    "readMinutes": 7,
    "tag": "ESP",
    "sections": [
      {
        "heading": "Weapon ESP",
        "body": [
          "Pair with distance — SMG at 90m is often a wounded player, not a bait."
        ]
      }
    ]
  },
  {
    "slug": "view-direction-lines",
    "title": "View Direction Lines: Spotting Enemy Flanks Before They Happen",
    "excerpt": "View direction lines show where a tag is looking — flank safely.",
    "metaTitle": "View Direction Lines: Spotting Enemy Flanks Before They Happen | Wardogs Cheats Forum",
    "metaDescription": "View direction lines show where a tag is looking — flank safely.",
    "searchTerms": "Wardogs ESP, view direction lines, Wardogs cheats",
    "date": "2026-09-14",
    "readMinutes": 8,
    "tag": "ESP",
    "sections": [
      {
        "heading": "View lines",
        "body": [
          "Disable on max clutter maps; keep for solo flanks on open hills."
        ]
      }
    ]
  },
  {
    "slug": "oof-arrows-guide",
    "title": "Out of Field Arrows: Off-Screen Threat Alerts Explained",
    "excerpt": "OOF arrows for sound-only contacts during control-zone rotates.",
    "metaTitle": "Out of Field Arrows: Off-Screen Threat Alerts Explained | Wardogs Cheats Forum",
    "metaDescription": "OOF arrows for sound-only contacts during control-zone rotates.",
    "searchTerms": "Wardogs ESP, oof arrows guide, Wardogs cheats",
    "date": "2026-09-15",
    "readMinutes": 9,
    "tag": "ESP",
    "sections": [
      {
        "heading": "OOF arrows",
        "body": [
          "Combine with radar — arrow color matches threat bearing."
        ]
      }
    ]
  },
  {
    "slug": "max-distance-filters",
    "title": "Optimizing Max Distance Filters to Clean Up Your Screen",
    "excerpt": "Max distance caps for 100-player lobbies without losing close threats.",
    "metaTitle": "Optimizing Max Distance Filters to Clean Up Your Screen | Wardogs Cheats Forum",
    "metaDescription": "Max distance caps for 100-player lobbies without losing close threats.",
    "searchTerms": "Wardogs ESP, max distance filters, Wardogs cheats",
    "date": "2026-09-16",
    "readMinutes": 10,
    "tag": "ESP",
    "sections": [
      {
        "heading": "Max distance",
        "body": [
          "150m baseline; drop to 100m in final circle style fights."
        ]
      }
    ]
  },
  {
    "slug": "vehicle-visuals-setup",
    "title": "Vehicle Visuals Setup: Locating All In-Game Transport",
    "excerpt": "Map-wide vehicle overlay tuning — silhouette colors, convoy spacing, and when to hide distant blips on road-heavy maps.",
    "metaTitle": "Vehicle Visuals Setup: Locating All In-Game Transport | Wardogs Cheats Forum",
    "metaDescription": "Map-wide vehicle overlay tuning — silhouette colors, convoy spacing, and when to hide distant blips on road-heavy maps.",
    "searchTerms": "wardogs esp",
    "date": "2026-09-17",
    "readMinutes": 6,
    "tag": "Vehicles",
    "sections": [
      {
        "heading": "Map-wide vehicle overlays",
        "body": [
          "Color-code transports vs heavier platforms before you touch occupied/empty — silhouette recognition beats toggling everything at once.",
          "On road-heavy rotations, hide vehicles beyond 350m so your HUD stays readable while your squad holds a hill."
        ]
      }
    ]
  },
  {
    "slug": "vehicle-esp-tracking",
    "title": "Full Vehicle ESP Tracking: Map Mobility Control Guide",
    "excerpt": "Track trucks and transports across control-zone rotations.",
    "metaTitle": "Full Vehicle ESP Tracking: Map Mobility Control Guide | Wardogs Cheats Forum",
    "metaDescription": "Track trucks and transports across control-zone rotations.",
    "searchTerms": "wardogs esp",
    "date": "2026-09-18",
    "readMinutes": 7,
    "tag": "Vehicles",
    "sections": [
      {
        "heading": "Tracking",
        "body": [
          "Mark vehicles on radar and ESP — dual cue prevents surprise road pushes."
        ]
      }
    ]
  },
  {
    "slug": "vehicle-type-identification",
    "title": "Vehicle Type Identification Overlays: Heavy Armor vs Transport",
    "excerpt": "Type labels distinguish fast transports from heavier platforms.",
    "metaTitle": "Vehicle Type Identification Overlays: Heavy Armor vs Transport | Wardogs Cheats Forum",
    "metaDescription": "Type labels distinguish fast transports from heavier platforms.",
    "searchTerms": "Wardogs Vehicles, vehicle type identification, Wardogs cheats",
    "date": "2026-09-19",
    "readMinutes": 8,
    "tag": "Vehicles",
    "sections": [
      {
        "heading": "Types",
        "body": [
          "Do not mag-dump light vehicles — type tag saves ammo for player tags inside."
        ]
      }
    ]
  },
  {
    "slug": "vehicle-distance-measure",
    "title": "Measuring Vehicle Distance for Strategic Encounters",
    "excerpt": "Vehicle distance for AT vs small arms decisions.",
    "metaTitle": "Measuring Vehicle Distance for Strategic Encounters | Wardogs Cheats Forum",
    "metaDescription": "Vehicle distance for AT vs small arms decisions.",
    "searchTerms": "Wardogs Vehicles, vehicle distance measure, Wardogs cheats",
    "date": "2026-09-20",
    "readMinutes": 9,
    "tag": "Vehicles",
    "sections": [
      {
        "heading": "Distance",
        "body": [
          "Hide vehicles beyond 400m if you only care about immediate road threats."
        ]
      }
    ]
  },
  {
    "slug": "occupied-empty-vehicles",
    "title": "Occupied vs Empty Vehicle Indicators: Ambush Prevention",
    "excerpt": "Empty truck bait vs occupied convoy — indicator saves pushes.",
    "metaTitle": "Occupied vs Empty Vehicle Indicators: Ambush Prevention | Wardogs Cheats Forum",
    "metaDescription": "Empty truck bait vs occupied convoy — indicator saves pushes.",
    "searchTerms": "Wardogs Vehicles, occupied empty vehicles, Wardogs cheats",
    "date": "2026-09-21",
    "readMinutes": 10,
    "tag": "Vehicles",
    "sections": [
      {
        "heading": "Occupied state",
        "body": [
          "Slow peek empty markers — players hide beside hull."
        ]
      }
    ]
  },
  {
    "slug": "radar-options-guide",
    "title": "2D Radar Options: Complete Minimap Awareness Guide",
    "excerpt": "Radar module overview for Wardogs minimap power users.",
    "metaTitle": "2D Radar Options: Complete Minimap Awareness Guide | Wardogs Cheats Forum",
    "metaDescription": "Radar module overview for Wardogs minimap power users.",
    "searchTerms": "Wardogs Radar, radar options guide, Wardogs cheats",
    "date": "2026-09-12",
    "readMinutes": 6,
    "tag": "Radar",
    "sections": [
      {
        "heading": "Radar options",
        "body": [
          "Player + vehicle markers together — toggle one off in final fights."
        ]
      }
    ]
  },
  {
    "slug": "custom-2d-radar-hud",
    "title": "Positioning Mastery: Setting Up a Custom 2D Radar HUD",
    "excerpt": "Radar size and corner placement on ultrawide vs 1080p.",
    "metaTitle": "Positioning Mastery: Setting Up a Custom 2D Radar HUD | Wardogs Cheats Forum",
    "metaDescription": "Radar size and corner placement on ultrawide vs 1080p.",
    "searchTerms": "Wardogs Radar, custom 2d radar hud, Wardogs cheats",
    "date": "2026-09-13",
    "readMinutes": 7,
    "tag": "Radar",
    "sections": [
      {
        "heading": "HUD placement",
        "body": [
          "Bottom-left stack above native minimap — avoid covering cash UI."
        ]
      }
    ]
  },
  {
    "slug": "player-markers-radar",
    "title": "Player Markers on Radar: Tracking Enemy Rotation Paths",
    "excerpt": "Read rotation arcs on 2D radar before third party sound.",
    "metaTitle": "Player Markers on Radar: Tracking Enemy Rotation Paths | Wardogs Cheats Forum",
    "metaDescription": "Read rotation arcs on 2D radar before third party sound.",
    "searchTerms": "Wardogs Radar, player markers radar, Wardogs cheats",
    "date": "2026-09-14",
    "readMinutes": 8,
    "tag": "Radar",
    "sections": [
      {
        "heading": "Player markers",
        "body": [
          "Watch marker velocity — sprinting tags toward control zone = rotate early."
        ]
      }
    ]
  },
  {
    "slug": "vehicle-markers-radar",
    "title": "Vehicle Radar Markers: High-Speed Threat Detection",
    "excerpt": "Fast blips on radar for road pushes and flanking trucks.",
    "metaTitle": "Vehicle Radar Markers: High-Speed Threat Detection | Wardogs Cheats Forum",
    "metaDescription": "Fast blips on radar for road pushes and flanking trucks.",
    "searchTerms": "Wardogs Radar, vehicle markers radar, Wardogs cheats",
    "date": "2026-09-15",
    "readMinutes": 9,
    "tag": "Radar",
    "sections": [
      {
        "heading": "Vehicle markers",
        "body": [
          "Pair with occupied ESP — empty blip still might have infantry nearby."
        ]
      }
    ]
  },
  {
    "slug": "radar-range-calibration",
    "title": "Calibrating Radar Range for Close and Long-Range Fights",
    "excerpt": "Radar range tuning for urban vs mountain maps.",
    "metaTitle": "Calibrating Radar Range for Close and Long-Range Fights | Wardogs Cheats Forum",
    "metaDescription": "Radar range tuning for urban vs mountain maps.",
    "searchTerms": "Wardogs Radar, radar range calibration, Wardogs cheats",
    "date": "2026-09-16",
    "readMinutes": 10,
    "tag": "Radar",
    "sections": [
      {
        "heading": "Range",
        "body": [
          "Short range in towns; widen when holding open hills between zones."
        ]
      }
    ]
  },
  {
    "slug": "misc-utility-features",
    "title": "Miscellaneous Utility Features for Ultimate Gameplay Control",
    "excerpt": "Misc menu: recoil, spread, brightness, crosshair, configs.",
    "metaTitle": "Miscellaneous Utility Features for Ultimate Gameplay Control | Wardogs Cheats Forum",
    "metaDescription": "Misc menu: recoil, spread, brightness, crosshair, configs.",
    "searchTerms": "Wardogs Misc, misc utility features, Wardogs cheats",
    "date": "2026-09-17",
    "readMinutes": 6,
    "tag": "Misc",
    "sections": [
      {
        "heading": "Misc stack",
        "body": [
          "No recoil/no spread are loud on spectator cams — use sparingly in public lobbies."
        ]
      }
    ]
  },
  {
    "slug": "no-recoil-compensation",
    "title": "Zero Recoil Compensation: Eliminating Weapon Kickback",
    "excerpt": "No recoil toggle habits for burst weapons in Wardogs.",
    "metaTitle": "Zero Recoil Compensation: Eliminating Weapon Kickback | Wardogs Cheats Forum",
    "metaDescription": "No recoil toggle habits for burst weapons in Wardogs.",
    "searchTerms": "Wardogs Misc, no recoil compensation, Wardogs cheats",
    "date": "2026-09-18",
    "readMinutes": 7,
    "tag": "Misc",
    "sections": [
      {
        "heading": "No recoil",
        "body": [
          "Tap fire still looks cleaner than full auto laser beams."
        ]
      }
    ]
  },
  {
    "slug": "no-spread-elimination",
    "title": "Perfect Bullet Spread Elimination: Laser-Accurate Firing",
    "excerpt": "No spread interaction with movement and jump shots.",
    "metaTitle": "Perfect Bullet Spread Elimination: Laser-Accurate Firing | Wardogs Cheats Forum",
    "metaDescription": "No spread interaction with movement and jump shots.",
    "searchTerms": "Wardogs Misc, no spread elimination, Wardogs cheats",
    "date": "2026-09-19",
    "readMinutes": 8,
    "tag": "Misc",
    "sections": [
      {
        "heading": "No spread",
        "body": [
          "Combine with moderate aimbot — max stack screams on kill cam."
        ]
      }
    ]
  },
  {
    "slug": "full-bright-toggles",
    "title": "Full Bright Visual Toggles: Max Visibility in Dark Map Areas",
    "excerpt": "Full bright for interior clears without cranking gamma globally.",
    "metaTitle": "Full Bright Visual Toggles: Max Visibility in Dark Map Areas | Wardogs Cheats Forum",
    "metaDescription": "Full bright for interior clears without cranking gamma globally.",
    "searchTerms": "Wardogs Misc, full bright toggles, Wardogs cheats",
    "date": "2026-09-20",
    "readMinutes": 9,
    "tag": "Misc",
    "sections": [
      {
        "heading": "Full bright",
        "body": [
          "Toggle off for screenshots — flat lighting looks unnatural in clips."
        ]
      }
    ]
  },
  {
    "slug": "custom-crosshair-overlays",
    "title": "Custom Crosshair Overlays for Hipfire and Precision Shooting",
    "excerpt": "Custom crosshair when iron sights clutter the screen.",
    "metaTitle": "Custom Crosshair Overlays for Hipfire and Precision Shooting | Wardogs Cheats Forum",
    "metaDescription": "Custom crosshair when iron sights clutter the screen.",
    "searchTerms": "Wardogs Misc, custom crosshair overlays, Wardogs cheats",
    "date": "2026-09-21",
    "readMinutes": 10,
    "tag": "Misc",
    "sections": [
      {
        "heading": "Crosshair",
        "body": [
          "Small dot for hipfire, circle for DMR — match native sight color."
        ]
      }
    ]
  },
  {
    "slug": "config-save-load",
    "title": "Fast Setup: How to Save and Load Your Custom Config Settings",
    "excerpt": "Config profiles for solo vs trio control-zone nights.",
    "metaTitle": "Fast Setup: How to Save and Load Your Custom Config Settings | Wardogs Cheats Forum",
    "metaDescription": "Config profiles for solo vs trio control-zone nights.",
    "searchTerms": "Wardogs Misc, config save load, Wardogs cheats",
    "date": "2026-09-12",
    "readMinutes": 6,
    "tag": "Misc",
    "sections": [
      {
        "heading": "Configs",
        "body": [
          "Save \"esp-only\", \"vehicles\", and \"full assist\" — load before queue."
        ]
      }
    ]
  },
  {
    "slug": "windows-setup",
    "title": "Wardogs Cheats on Windows 10 and 11",
    "excerpt": "Windows prep for Wardogs cheats — overlays, Defender, TPM/HVCI notes.",
    "metaTitle": "Wardogs Cheats on Windows 10 and 11 | Wardogs Cheats Forum",
    "metaDescription": "Windows prep for Wardogs cheats — overlays, Defender, TPM/HVCI notes.",
    "searchTerms": "Wardogs Windows, windows setup, Wardogs cheats",
    "date": "2026-09-13",
    "readMinutes": 7,
    "tag": "Windows",
    "sections": [
      {
        "heading": "Supported systems",
        "body": [
          "Windows 10/11 with Steam Wardogs — close overlays before inject."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "disable-antivirus",
    "title": "Antivirus Exclusions for Wardogs Cheats",
    "excerpt": "Allowlist loaders in Defender so files are not quarantined mid-setup.",
    "metaTitle": "Antivirus Exclusions for Wardogs Cheats | Wardogs Cheats Forum",
    "metaDescription": "Allowlist loaders in Defender so files are not quarantined mid-setup.",
    "searchTerms": "Wardogs Antivirus, disable antivirus, Wardogs cheats",
    "date": "2026-09-14",
    "readMinutes": 8,
    "tag": "Antivirus",
    "sections": [
      {
        "heading": "Defender",
        "body": [
          "Folder exclusion before first run — restore quarantines if you retried blindly."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "hotkeys",
    "title": "Wardogs Cheat Hotkeys After Load",
    "excerpt": "Menu and toggle hotkeys — ESP, aimbot, radar panic binds.",
    "metaTitle": "Wardogs Cheat Hotkeys After Load | Wardogs Cheats Forum",
    "metaDescription": "Menu and toggle hotkeys — ESP, aimbot, radar panic binds.",
    "searchTerms": "Wardogs Hotkeys, hotkeys, Wardogs cheats",
    "date": "2026-09-15",
    "readMinutes": 9,
    "tag": "Hotkeys",
    "sections": [
      {
        "heading": "Suggested binds",
        "body": [
          "Menu toggle, ESP master, aimbot toggle, radar toggle — write them down once."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "loader-errors",
    "title": "Fix Wardogs Cheat Loader Errors",
    "excerpt": "Menu not opening, instant close, antivirus quarantine, failed inject.",
    "metaTitle": "Fix Wardogs Cheat Loader Errors | Wardogs Cheats Forum",
    "metaDescription": "Menu not opening, instant close, antivirus quarantine, failed inject.",
    "searchTerms": "Wardogs Support, loader errors, Wardogs cheats",
    "date": "2026-09-16",
    "readMinutes": 10,
    "tag": "Support",
    "sections": [
      {
        "heading": "Check status first",
        "body": [
          "Updating builds fail for reasons settings cannot fix — confirm Active."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "load-status-checklist",
    "title": "Pre-Load Checklist Before You Buy or Queue",
    "excerpt": "Confirm Active status, game version, and config before ranked-style queues.",
    "metaTitle": "Pre-Load Checklist Before You Buy or Queue | Wardogs Cheats Forum",
    "metaDescription": "Confirm Active status, game version, and config before ranked-style queues.",
    "searchTerms": "Wardogs Status, load status checklist, Wardogs cheats",
    "date": "2026-09-17",
    "readMinutes": 6,
    "tag": "Status",
    "sections": [
      {
        "heading": "Before checkout",
        "body": [
          "Confirm Active on cheatforwardogs.net. If Updating, wait or read refunds policy."
        ]
      }
    ]
  }
]

export function getBlog(slug: string) {
  return BLOGS.find((b) => b.slug === slug)
}

/** Related threads for forum footers — never includes the current slug. */
export function getRelatedForumThreads(slug: string, limit = 6): BlogPost[] {
  const current = getBlog(slug)
  if (!current) return []
  return BLOGS.filter((b) => b.slug !== slug)
    .sort((a, b) => {
      const tagRank = (p: BlogPost) => (p.tag === current.tag ? 0 : 1)
      const byTag = tagRank(a) - tagRank(b)
      if (byTag !== 0) return byTag
      return a.title.localeCompare(b.title)
    })
    .slice(0, limit)
}

export { blogPath } from './blog-paths'
